// <auto-generated />
using System;
using FinanceApplication.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceApplication.Migrations
{
    [DbContext(typeof(MVCdbdemo))]
    [Migration("20231028134129_add-id")]
    partial class addid
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinanceApplication.Models.domain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("entitymodellistsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("entitymodellistsId");

                    b.ToTable("domain");
                });

            modelBuilder.Entity("FinanceApplication.Models.entity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("entitymodellistsId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("entitymodellistsId");

                    b.ToTable("entities");
                });

            modelBuilder.Entity("FinanceApplication.Models.entitymodellists", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.HasKey("Id");

                    b.ToTable("entitymodellists");
                });

            modelBuilder.Entity("FinanceApplication.Models.transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.Property<string>("dom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("dt")
                        .HasColumnType("datetime2");

                    b.Property<int>("eId")
                        .HasColumnType("int");

                    b.Property<string>("ent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tratype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("eId");

                    b.ToTable("transaction");
                });

            modelBuilder.Entity("FinanceApplication.Models.domain", b =>
                {
                    b.HasOne("FinanceApplication.Models.entitymodellists", null)
                        .WithMany("domainview")
                        .HasForeignKey("entitymodellistsId");
                });

            modelBuilder.Entity("FinanceApplication.Models.entity", b =>
                {
                    b.HasOne("FinanceApplication.Models.entitymodellists", null)
                        .WithMany("entityview")
                        .HasForeignKey("entitymodellistsId");
                });

            modelBuilder.Entity("FinanceApplication.Models.transaction", b =>
                {
                    b.HasOne("FinanceApplication.Models.entitymodellists", "e")
                        .WithMany()
                        .HasForeignKey("eId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("e");
                });

            modelBuilder.Entity("FinanceApplication.Models.entitymodellists", b =>
                {
                    b.Navigation("domainview");

                    b.Navigation("entityview");
                });
#pragma warning restore 612, 618
        }
    }
}
