// <auto-generated />
using System;
using FinanceApplication.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinanceApplication.Migrations
{
    [DbContext(typeof(MVCdbdemo))]
    partial class MVCdbdemoModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FinanceApplication.Models.domain", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("domain");
                });

            modelBuilder.Entity("FinanceApplication.Models.entity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("entities");
                });

            modelBuilder.Entity("FinanceApplication.Models.transaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("amount")
                        .HasColumnType("int");

                    b.Property<Guid>("domainfortransId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("dt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("entityfortransId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("tratype")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("domainfortransId");

                    b.HasIndex("entityfortransId");

                    b.ToTable("transaction");
                });

            modelBuilder.Entity("FinanceApplication.Models.transaction", b =>
                {
                    b.HasOne("FinanceApplication.Models.domain", "domainfortrans")
                        .WithMany()
                        .HasForeignKey("domainfortransId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinanceApplication.Models.entity", "entityfortrans")
                        .WithMany()
                        .HasForeignKey("entityfortransId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("domainfortrans");

                    b.Navigation("entityfortrans");
                });
#pragma warning restore 612, 618
        }
    }
}
